# https://taskfile.dev

version: '3'

#begin vars
vars:
  OUT: marp-simple.png
  DIST: ~/PPM/img
#end vars

tasks:
#begin build
  build:
    cmds:
      - marp marp-simple.md -o marp-simple.png
    silent: true
#end build

#begin default
  default:
    desc: copy to course slides
    deps:
      - build
    cmds:
      - cp {{.OUT}} {{.DIST}}/{{.OUT}}
#end default

  pandoc:
    desc: Use pandoc
    cmds:
      - pandoc marp-simple.md -o marp-simple-pandoc.pptx

  marp:
    desc: Use marp for powerpoint
    cmds:
      - marp marp-simple.md -o marp-simple-marp.pptx
