# https://taskfile.dev

version: '3'

vars:
  OUT: markdown.png
  DIST: ~/PPM/img
  OPT: "--allow-local-files --images png"

tasks:
#begin build
  build:
    cmds:
      - marp {{.OPT}} markdown.md -o {{.OUT}}
    silent: true
#end build

  default:
    desc: copy to course slides
    deps:
      - build
    cmds:
      - cp *.png {{.DIST}}/