# https://taskfile.dev

version: '3'

vars:  
  DIST: ~/PPM/img


tasks:
  build:
    desc: Output png
    cmds:
      - marp mermaid.md --html -o mermaid.png
    silent: true

  default:
    desc: copy to course slides
    deps:
      - build
    cmds:
      - cp mermaid.png {{.DIST}}/mermaid.png
