# https://taskfile.dev

version: '3'

vars:
  OUT: marp-code.png
  DIST: ~/PPM/img

tasks:
#begin build
  build:
    cmds:
      - marp marp-code.md -o {{.OUT}}
    silent: true
#end build

  default:
    desc: copy to course slides
    deps:
      - build
    cmds:
      - cp {{.OUT}} {{.DIST}}/{{.OUT}}